apiVersion: v1
kind: Pod
metadata:
  name: workstation
  labels:
    app: workstation
spec:
  containers:
    - name: main
      image: codercom/code-server
      env:
        - name: PASSWORD
          value: password
      ports:
        - containerPort: 8080
