apiVersion: v1
kind: Pod
metadata:
  name: workstation
  labels:
    app: workstation
spec:
  containers:
    - name: main
      image: codercom/code-server
      env:
        - name: PASSWORD
          value: password
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workstation-service
spec:
  type: LoadBalancer
  selector:
    app: workstation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
